# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "trusty"
    config.vm.box_url = "https://dl.dropboxusercontent.com/u/4311762/box-disk2.vmdk.zip"
    config.vm.network "forwarded_port", guest: 8000, host: 8000

    config.vm.provision :chef_solo do |chef|
        chef.recipe_url = "https://dl.dropbox.com/u/4311762/cookbooks.tar.gz"
        chef.cookbooks_path = [:vm, "cookbooks"]

        chef.add_recipe "main"
        chef.add_recipe "python"
        chef.add_recipe "less"
        chef.add_recipe "mysql"

        chef.json.merge!({
            :project_name => "test",
            :system_packages => [],
            :oh_my_zsh => {
                :theme => "cloud",
                :plugins => ["git"]
            },
            :python_global_packages => ["bpython", "git+git://github.com/Lokaltog/powerline"],
            :python_packages => [],
            :mysql => {
                :root_password => "root"
            }
        })
    end
end
