# vi: set ft=ruby :
Vagrant::Config.run do |config|
    config.vm.box = "quantal64"
    config.vm.box_url = "https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box"

    config.vm.forward_port 8000, 8000
    config.vm.network :hostonly, "33.33.00.10"
    # Used only in some rare cases
    #config.vm.share_folder("vagrant-root", "/vagrant", ".", :extra => 'dmode=770,fmode=770', :nfs => true)

    config.vm.provision :chef_solo do |chef|
        chef.recipe_url = "https://dl.dropbox.com/u/4311762/cookbooks.tar.gz"
        chef.cookbooks_path = [:vm, "cookbooks"]

        chef.add_recipe "main"
        chef.add_recipe "python"
        chef.add_recipe "less"
        chef.add_recipe "mysql"

        chef.json.merge!({
            :project_name => "test",
            :system_packages => [],
            :oh_my_zsh => {
                :theme => "cloud",
                :plugins => ["git"]
            },
            :python_global_packages => ["bpython"],
            :python_packages => [],
            :mysql => {
                :root_password => "root"
            }
        })
    end
end

